const quotes = ['Currently having trouble exiting vim :qwkjhklrkjewhrlkwh', 
    'Unblock pls @VMo917', 
    'MorrisBot 2024!',
    'Shoutout to my fav students! Matt, Dylan, Isaque, Jacques, Evan, Jack and Alistair!',
    'Follow for follow? @VMo917',
    'Over 1 Tweet and counting! @VMo917',
    'The Verndog',
    'Hello 👋 @VMo917',
    'Eliam Hernandez is killing me!',
    'Help Make Gambling Legal In NY! I hate driving to New Jersey',
    "I'm Still waiting for that follow back @VMo917",
    "Stop using Internet Explorer, Jayden",
    "Guys, please stop talking. You need to know this stuff.",
    "",
    "",
    "",
    "",
    "",

];